
version: '3.7'

services:
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: server
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pizza_admin
      - POSTGRES_PASSWORD=pizza_admin
      - POSTGRES_DB=pizza_db
volumes:
  postgres_data:
